// GENERATED by tools/build-core.mjs from data/skills/*.json — do not edit by hand.
import type { Skill } from './model.ts'

export const SKILLS: Skill[] = [
 {
  "id": "joint-prep-wrists",
  "name": "Wrist Prep",
  "branch": "Physical Foundations",
  "family": "cal",
  "req": [],
  "tiers": {
   "u": "Wrist extension tolerance built (rocks, lifts)",
   "p": "Fingertip rocks, first-knuckle push-ups + planche-lean prep pain-free",
   "m": "Wrists never the limiting factor"
  },
  "kind": "foundation",
  "note": "Load-bearing gate for the planche line"
 },
 {
  "id": "scapular-control",
  "name": "Scapular Control",
  "branch": "Physical Foundations",
  "family": "cal",
  "req": [],
  "tiers": {
   "u": "Protraction/retraction on floor, elevation/depression on bar",
   "p": "Holds each position 10s under load",
   "m": "Scap position automatic in every push and pull"
  },
  "kind": "foundation"
 },
 {
  "id": "hollow-arch-basics",
  "name": "Hollow & Arch Hold",
  "branch": "Physical Foundations",
  "family": "cal",
  "req": [],
  "tiers": {
   "u": "30s hollow hold + 30s arch hold",
   "p": "Bodyline held through rocks",
   "m": "Line awareness carries into every skill"
  },
  "kind": "foundation"
 },
 {
  "id": "compression-foundation",
  "name": "Compression Foundation",
  "branch": "Physical Foundations",
  "family": "cal",
  "req": [
   "hollow-arch-basics",
   "pike-compression-stretch"
  ],
  "tiers": {
   "u": "Seated leg lifts ×10",
   "p": "Pike pulses + active flexibility weekly",
   "m": "Compression strong enough for L-sit/V-sit work"
  },
  "kind": "foundation"
 },
 {
  "id": "assisted-pushup",
  "name": "Assisted Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [],
  "unit": "reps",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "pushup",
  "name": "Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "assisted-pushup"
  ],
  "unit": "reps",
  "t": [
   10,
   20,
   40
  ],
  "star": true,
  "note": "2026 goal: 40 push-ups"
 },
 {
  "id": "decline-pushup",
  "name": "Decline Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   15,
   25,
   40
  ]
 },
 {
  "id": "diamond-pushup",
  "name": "Diamond Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   8,
   15,
   25
  ]
 },
 {
  "id": "archer-pushup",
  "name": "Archer Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "uneven-pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   12,
   20
  ]
 },
 {
  "id": "bicep-pushup",
  "name": "Bicep Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "diamond-pushup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "oap-eccentric",
  "name": "One-Arm Push-Up Negative",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "archer-pushup"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "Slow 5s lowering, square hips"
 },
 {
  "id": "one-arm-pushup",
  "name": "One-Arm Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "oap-eccentric"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   8
  ],
  "star": true
 },
 {
  "id": "dip",
  "name": "Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   20
  ]
 },
 {
  "id": "weighted-dip",
  "name": "Weighted Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "kg added",
  "t": [
   5,
   15,
   25
  ],
  "note": "5 clean reps at the listed added weight"
 },
 {
  "id": "support-hold",
  "name": "Support Hold",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "sec",
  "t": [
   15,
   30,
   60
  ],
  "kind": "bridge",
  "note": "Parallel bar / ring support — gates deeper pushing and L-sit work"
 },
 {
  "id": "straight-bar-dip",
  "name": "Straight Bar Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "The specific muscle-up dip position"
 },
 {
  "id": "elbow-lever",
  "name": "Elbow Lever",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   20
  ]
 },
 {
  "id": "planche-lean",
  "name": "Planche Lean",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip",
   "joint-prep-wrists"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "frog-stand-to-tuck",
  "name": "Frog Stand > Tuck",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "planche-lean"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   20
  ],
  "kind": "bridge",
  "note": "Bridge between crow/elbow lever and tuck planche — knees off the elbows"
 },
 {
  "id": "planche-lean-pushup",
  "name": "Planche Lean Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "planche-lean"
  ],
  "unit": "reps",
  "t": [
   3,
   8,
   15
  ],
  "kind": "bridge"
 },
 {
  "id": "pseudo-pushup",
  "name": "Pseudo Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "planche-lean-pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   20
  ]
 },
 {
  "id": "tuck-planche",
  "name": "Tuck Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pseudo-pushup",
   "frog-stand-to-tuck"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "planche-program-8wk",
  "name": "8-Week Planche Block",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pseudo-pushup",
   "tuck-planche"
  ],
  "tiers": {
   "u": "Block written: days, volume, progressions",
   "p": "4 weeks in, holds measured weekly",
   "m": "Block complete — measured gain in tuck hold"
  },
  "kind": "milestone",
  "note": "First measured planche block"
 },
 {
  "id": "tuck-planche-pushup",
  "name": "Tuck Planche Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "tuck-planche"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   6
  ]
 },
 {
  "id": "adv-tuck-planche",
  "name": "Adv. Tuck Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "tuck-planche"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "adv-tuck-planche-pushup",
  "name": "Adv. Tuck Planche Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "adv-tuck-planche"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "straddle-planche",
  "name": "Straddle Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "piked-straddle-planche"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "ninety-deg-hold",
  "name": "90° Hold",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "straddle-planche"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   10
  ]
 },
 {
  "id": "ninety-deg-pushup",
  "name": "90° Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "ninety-deg-hold"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "2026 goal: 1 clean 90° push-up"
 },
 {
  "id": "full-planche",
  "name": "Full Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "half-lay-planche"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   10
  ],
  "star": true
 },
 {
  "id": "planche-pushup",
  "name": "Planche Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "full-planche"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "star": true,
  "note": "Triple-crown piece #1"
 },
 {
  "id": "wide-pushup",
  "name": "Wide Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   12,
   22,
   40
  ],
  "note": "Wider grip, arms still <45° from torso — pec emphasis"
 },
 {
  "id": "uneven-pushup",
  "name": "Uneven Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "diamond-pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   16
  ],
  "note": "One hand elevated — bridge toward the one-arm push-up"
 },
 {
  "id": "spiderman-pushup",
  "name": "Spider-Man Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   8,
   15,
   25
  ],
  "note": "Knee draws to elbow each rep — obliques + hip stability"
 },
 {
  "id": "scorpion-pushup",
  "name": "Scorpion Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "spiderman-pushup"
  ],
  "unit": "reps",
  "t": [
   6,
   12,
   20
  ],
  "note": "Vrishchik dand — leg kicks high on the twist, posterior chain"
 },
 {
  "id": "tigerbend-pushup",
  "name": "Tiger Bend Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   14
  ],
  "note": "Lowers onto forearms then presses back — condition elbows slowly"
 },
 {
  "id": "hindu-pushup",
  "name": "Hindu Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   8,
   15,
   25
  ],
  "note": "Sadharan dand — dive-and-scoop flow"
 },
 {
  "id": "dive-bomber-pushup",
  "name": "Dive Bomber Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "hindu-pushup"
  ],
  "unit": "reps",
  "t": [
   6,
   12,
   20
  ],
  "note": "Ram murti dand — hindu that reverses back through the same arc"
 },
 {
  "id": "straddle-planche-pushup",
  "name": "Straddle Planche Push-Up",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "straddle-planche",
   "adv-tuck-planche-pushup"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   6
  ]
 },
 {
  "id": "bench-dip",
  "name": "Bench Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   10,
   18,
   30
  ],
  "note": "Feet-supported entry to the dip pattern"
 },
 {
  "id": "bulgarian-dip",
  "name": "Bulgarian Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   16
  ],
  "note": "Wide arms, 90° at the bottom — rear delt / lat emphasis"
 },
 {
  "id": "chest-dip",
  "name": "Chest Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "reps",
  "t": [
   6,
   12,
   20
  ],
  "note": "Forward lean, legs ahead — pec emphasis"
 },
 {
  "id": "archer-dip",
  "name": "Archer Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "chest-dip"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ],
  "note": "Straight archer arm acts like a bodyweight pec fly"
 },
 {
  "id": "rto-support-hold",
  "name": "RTO Support Hold",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "support-hold",
   "planche-lean"
  ],
  "unit": "sec",
  "t": [
   10,
   30,
   60
  ],
  "kind": "bridge",
  "note": "Rings-turned-out support — gates planche, iron cross, muscle-up work"
 },
 {
  "id": "rto-dip",
  "name": "RTO Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "rto-support-hold"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   12
  ],
  "note": "Rings-turned-out dip — needs skin-the-cat-level shoulder mobility first"
 },
 {
  "id": "korean-dip",
  "name": "Korean Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "dip"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "note": "Behind-the-body dip — condition shoulders; feeds back lever / hefesto"
 },
 {
  "id": "elbow-dip",
  "name": "Elbow Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "weighted-dip"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   14
  ],
  "note": "Tiger-bend analog on parallel bars"
 },
 {
  "id": "russian-dip",
  "name": "Russian Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "elbow-dip"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "note": "Elbow dip taken all the way to shoulder-on-bar"
 },
 {
  "id": "impossible-dip",
  "name": "Impossible Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "russian-dip"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   6
  ],
  "star": true,
  "note": "Elbows >90° the whole way, no kip — among the hardest tricep isolations"
 },
 {
  "id": "frog-planche",
  "name": "Frog Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "adv-tuck-planche"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "piked-straddle-planche",
  "name": "Piked-Straddle Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "frog-planche"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "half-lay-planche",
  "name": "Half-Lay Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "straddle-planche"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   12
  ]
 },
 {
  "id": "wide-grip-planche",
  "name": "Wide-Grip Planche",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "full-planche"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   10
  ]
 },
 {
  "id": "iron-cross-fly",
  "name": "Iron Cross Fly",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "rto-support-hold"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Dynamic bodyweight fly toward the cross"
 },
 {
  "id": "straight-arm-rto-dip",
  "name": "Iron Cross Dip",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "rto-dip"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Straight-arm RTO dip — the eccentric of the cross"
 },
 {
  "id": "iron-cross",
  "name": "Iron Cross",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "iron-cross-fly",
   "straight-arm-rto-dip"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ],
  "star": true,
  "note": "Dream tier — rings statics"
 },
 {
  "id": "maltese",
  "name": "Maltese",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "full-planche",
   "iron-cross"
  ],
  "unit": "sec",
  "t": [
   1,
   3,
   5
  ],
  "star": true,
  "note": "Dream tier — planche brought down to ring height"
 },
 {
  "id": "pelican-curl",
  "name": "Pelican Curl",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "rto-support-hold"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ],
  "kind": "bridge",
  "note": "Pseudo-hefesto — deep straight-ish-arm ring curl"
 },
 {
  "id": "hefesto",
  "name": "Hefesto",
  "branch": "Horizontal Push",
  "family": "cal",
  "req": [
   "pelican-curl"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   4
  ],
  "star": true,
  "note": "Behind-the-back ring curl — elite bicep/elbow strength"
 },
 {
  "id": "pike-pushup",
  "name": "Pike Push-Up",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   20
  ]
 },
 {
  "id": "elevated-pike-pushup",
  "name": "Elevated Pike Push-Up",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "pike-pushup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "crow-pose",
  "name": "Crow Pose",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "pike-pushup"
  ],
  "unit": "sec",
  "t": [
   10,
   30,
   60
  ],
  "note": "Mastered — 60s hold"
 },
 {
  "id": "assisted-handstand",
  "name": "Assisted Handstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "crow-pose"
  ],
  "unit": "sec",
  "t": [
   20,
   45,
   60
  ]
 },
 {
  "id": "wall-handstand",
  "name": "Wall Handstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "assisted-handstand"
  ],
  "unit": "sec",
  "t": [
   15,
   30,
   60
  ]
 },
 {
  "id": "wall-line-drill",
  "name": "Wall Line Drill",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "wall-handstand"
  ],
  "unit": "sec",
  "t": [
   20,
   40,
   60
  ],
  "kind": "bridge",
  "note": "Chest-to-wall bodyline, ribs tucked"
 },
 {
  "id": "handstand-bail",
  "name": "Handstand Bail",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "wall-handstand"
  ],
  "tiers": {
   "u": "Cartwheel bail one side, every time",
   "p": "Both sides on demand",
   "m": "Bailing is reflex — no fear off the wall"
  },
  "kind": "bridge"
 },
 {
  "id": "toe-pulls",
  "name": "Toe Pulls",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "wall-line-drill"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ],
  "kind": "bridge",
  "note": "Balance work off the wall"
 },
 {
  "id": "freestanding-kickups",
  "name": "Freestanding Kick-Ups",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "handstand-bail"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Controlled kick-up entries — reps that land in balance"
 },
 {
  "id": "handstand-shape",
  "name": "Handstand Shape",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "toe-pulls"
  ],
  "tiers": {
   "u": "Line checked on video: shoulders elevated",
   "p": "Ribs in, pelvis neutral, legs squeezed",
   "m": "The line looks gymnast-clean on film"
  },
  "kind": "bridge"
 },
 {
  "id": "handstand",
  "name": "Handstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "toe-pulls",
   "freestanding-kickups"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   20
  ],
  "star": true,
  "note": "Prime goal. 2026: 10s, then 20s. Balance drills first, not just wall time."
 },
 {
  "id": "assisted-hspu",
  "name": "Assisted Handstand Push-Up",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "wall-handstand",
   "elevated-pike-pushup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "hspu",
  "name": "Handstand Push-Up",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "assisted-hspu",
   "handstand"
  ],
  "unit": "reps",
  "t": [
   1,
   5,
   10
  ]
 },
 {
  "id": "freestanding-hspu",
  "name": "Freestanding HSPU",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "hspu"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "press-to-handstand",
  "name": "Press to Handstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "handstand",
   "pancake"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "Straddle press. Needs pancake flexibility (Mobility realm)."
 },
 {
  "id": "one-arm-handstand",
  "name": "One-Arm Handstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "press-to-handstand",
   "freestanding-hspu"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ],
  "star": true,
  "note": "Dream tier — years-long project"
 },
 {
  "id": "shoulder-stand",
  "name": "Shoulder Stand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [],
  "unit": "sec",
  "t": [
   20,
   40,
   60
  ]
 },
 {
  "id": "headstand",
  "name": "Headstand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "shoulder-stand"
  ],
  "unit": "sec",
  "t": [
   15,
   30,
   45
  ]
 },
 {
  "id": "forearm-stand",
  "name": "Forearm Stand",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "headstand"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "close-grip-pike-pushup",
  "name": "Close-Grip Pike Push-Up",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "pike-pushup"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   14
  ],
  "note": "Elbows tucked — anterior-delt emphasis, HSPU balance prep"
 },
 {
  "id": "close-grip-hspu",
  "name": "Close-Grip HSPU",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "hspu"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   6
  ],
  "note": "Narrow hands — harder anterior-delt-biased press"
 },
 {
  "id": "tigerbend-hspu",
  "name": "Tiger Bend HSPU",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "tigerbend-pushup",
   "hspu"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   5
  ],
  "note": "Lower to forearms in a handstand then press out — condition elbows first"
 },
 {
  "id": "hspu-90",
  "name": "90° HSPU",
  "branch": "Vertical Push",
  "family": "cal",
  "req": [
   "freestanding-hspu"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   4
  ],
  "note": "HSPU into a bent-elbow planche (elbow-lever) position"
 },
 {
  "id": "dead-hang",
  "name": "Dead Hang",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [],
  "unit": "sec",
  "t": [
   45,
   90,
   120
  ],
  "star": true
 },
 {
  "id": "active-hang",
  "name": "Active Hang",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "dead-hang"
  ],
  "unit": "sec",
  "t": [
   20,
   40,
   60
  ],
  "note": "Mastered — 60s"
 },
 {
  "id": "german-hang",
  "name": "German Hang",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "dead-hang"
  ],
  "unit": "sec",
  "t": [
   20,
   30,
   40
  ],
  "note": "Mastered — 40s baseline"
 },
 {
  "id": "skin-the-cat",
  "name": "Skin the Cat",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "german-hang"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "1 clean skin + un-skin (2026 completed)"
 },
 {
  "id": "rope-climb",
  "name": "Rope Climb",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "active-hang"
  ],
  "unit": "climbs",
  "t": [
   1,
   2,
   3
  ],
  "note": "Full rope climb"
 },
 {
  "id": "hanging-leg-raise",
  "name": "Hanging Leg Raise",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "active-hang"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "toes-to-bar",
  "name": "Toes to Bar",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "hanging-leg-raise"
  ],
  "unit": "reps",
  "t": [
   5,
   8,
   12
  ]
 },
 {
  "id": "scapula-pullup",
  "name": "Scapula Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "active-hang"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "assisted-pullup",
  "name": "Assisted Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "scapula-pullup"
  ],
  "unit": "reps",
  "t": [
   5,
   10,
   15
  ],
  "note": "Mastered implied — 8 strict pull-ups on record"
 },
 {
  "id": "pullup",
  "name": "Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "assisted-pullup"
  ],
  "unit": "reps",
  "t": [
   5,
   12,
   25
  ],
  "star": true,
  "note": "Current 8 reps (Jul 2026). 2026 goal: 25."
 },
 {
  "id": "chin-up",
  "name": "Chin-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "assisted-pullup"
  ],
  "unit": "reps",
  "t": [
   8,
   15,
   30
  ],
  "star": true,
  "note": "2026 goal: 30"
 },
 {
  "id": "chest-pullup",
  "name": "Chest-to-Bar Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "pullup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "archer-pullup",
  "name": "Archer Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "chest-pullup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "weighted-pullup",
  "name": "Weighted Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "pullup"
  ],
  "unit": "kg added",
  "t": [
   5,
   15,
   30
  ],
  "note": "5 clean reps at the listed added weight"
 },
 {
  "id": "explosive-pullup-chest",
  "name": "Explosive Chest Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "chest-pullup"
  ],
  "unit": "reps",
  "t": [
   3,
   5,
   8
  ],
  "kind": "bridge",
  "note": "Cleaner bridge before waist pull-ups — speed off the bottom"
 },
 {
  "id": "waist-pullup",
  "name": "Explosive Waist Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "explosive-pullup-chest"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "pullover",
  "name": "Pullover",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "waist-pullup"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   3
  ]
 },
 {
  "id": "false-grip-transition",
  "name": "False Grip & Transition Prep",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "pullup",
   "dip"
  ],
  "tiers": {
   "u": "False grip hang 15s",
   "p": "Slow transition mechanics on low bar/rings",
   "m": "Transition position feels natural"
  },
  "kind": "bridge"
 },
 {
  "id": "banded-muscle-up-transition",
  "name": "Banded MU Transition",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "explosive-pullup-chest",
   "straight-bar-dip",
   "false-grip-transition"
  ],
  "unit": "reps",
  "t": [
   3,
   5,
   8
  ],
  "kind": "bridge",
  "note": "Low-risk transition drill"
 },
 {
  "id": "muscle-up-negative",
  "name": "Muscle-Up Negative",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "banded-muscle-up-transition"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "kind": "bridge",
  "note": "Controlled descent through the transition"
 },
 {
  "id": "muscle-up",
  "name": "Muscle-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "waist-pullup",
   "muscle-up-negative"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "star": true,
  "note": "2026 goal: 1 explosive muscle-up. Transition prep first — not just pulling height."
 },
 {
  "id": "strict-muscle-up",
  "name": "Strict Muscle-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "muscle-up"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "No kip, no chicken-wing"
 },
 {
  "id": "oap-negative",
  "name": "One-Arm Pull-Up Negative",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "archer-pullup",
   "weighted-pullup"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "5s+ controlled lowering"
 },
 {
  "id": "one-arm-pullup",
  "name": "One-Arm Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "oap-negative"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   5
  ],
  "star": true,
  "note": "Triple-crown piece #2"
 },
 {
  "id": "dead-hang-human-flag",
  "name": "Dead-Hang Human Flag",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "pullup",
   "dip"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Kick up and hold, body still hanging under the top hand — the flag entry"
 },
 {
  "id": "tuck-human-flag",
  "name": "Tuck Human Flag",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "dead-hang-human-flag"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   8
  ]
 },
 {
  "id": "straddle-human-flag",
  "name": "Straddle Human Flag",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "tuck-human-flag"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   8
  ]
 },
 {
  "id": "human-flag",
  "name": "Human Flag",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "straddle-human-flag"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   10
  ],
  "star": true
 },
 {
  "id": "headbangers",
  "name": "Headbangers",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "chest-pullup"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   12
  ],
  "note": "Pull the body horizontally away from the bar and back — explosive prep"
 },
 {
  "id": "typewriter-pullup",
  "name": "Typewriter Pull-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "chest-pullup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "note": "Traverse side to side at the top — unilateral overload"
 },
 {
  "id": "oac-negative",
  "name": "One-Arm Chin-Up Negative",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "chin-up"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "Supinated 5s+ lowering — the OAC bridge"
 },
 {
  "id": "one-arm-chinup",
  "name": "One-Arm Chin-Up",
  "branch": "Vertical Pull",
  "family": "cal",
  "req": [
   "oac-negative"
  ],
  "unit": "reps",
  "t": [
   1,
   2,
   4
  ],
  "star": true,
  "note": "Supinated one-arm — usually reached before the pronated OAP"
 },
 {
  "id": "assisted-inverted-row",
  "name": "Assisted Inverted Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [],
  "unit": "reps",
  "t": [
   10,
   15,
   25
  ]
 },
 {
  "id": "inverted-row",
  "name": "Inverted Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "assisted-inverted-row"
  ],
  "unit": "reps",
  "t": [
   8,
   12,
   25
  ]
 },
 {
  "id": "bulgarian-row",
  "name": "Bulgarian Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "inverted-row"
  ],
  "unit": "reps",
  "t": [
   6,
   12,
   20
  ],
  "note": "Wide 90°/90° grip — rear-delt emphasis"
 },
 {
  "id": "one-arm-inverted-row",
  "name": "One-Arm Inverted Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "inverted-row"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   14
  ],
  "note": "Torso square to the ring tension — unilateral horizontal pull"
 },
 {
  "id": "tuck-fl",
  "name": "Tuck Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "inverted-row",
   "pullup"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   20
  ],
  "note": "15s hit (2026 completed) — 20s = mastery"
 },
 {
  "id": "front-lever-raises-tuck",
  "name": "Tuck FL Raises",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "tuck-fl"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Dynamic strength bridge — raise to tuck FL and lower"
 },
 {
  "id": "tuck-fl-row",
  "name": "Tuck Front Lever Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "tuck-fl"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ]
 },
 {
  "id": "single-leg-tuck-fl",
  "name": "Single-Leg Tuck Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "tuck-fl"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "adv-single-leg-tuck-fl",
  "name": "Adv. Single-Leg Tuck FL",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "single-leg-tuck-fl"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "adv-tuck-fl-row",
  "name": "Adv. Tuck FL Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "tuck-fl-row",
   "adv-single-leg-tuck-fl"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "front-lever-negatives",
  "name": "Front Lever Negatives",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "adv-single-leg-tuck-fl"
  ],
  "unit": "reps",
  "t": [
   3,
   5,
   8
  ],
  "kind": "bridge",
  "note": "Controlled lower from inverted to hang"
 },
 {
  "id": "piked-straddle-front-lever",
  "name": "Piked-Straddle Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "adv-single-leg-tuck-fl"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "straddle-fl",
  "name": "Straddle Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "piked-straddle-front-lever"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "half-lay-front-lever",
  "name": "Half-Lay Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "straddle-fl"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   12
  ]
 },
 {
  "id": "straddle-fl-row",
  "name": "Straddle FL Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "straddle-fl"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "full-fl",
  "name": "Full Front Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "half-lay-front-lever"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ],
  "star": true,
  "note": "Triple-crown piece #3. 2026 goal: 15s."
 },
 {
  "id": "full-fl-row",
  "name": "Front Lever Row",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "full-fl",
   "straddle-fl-row"
  ],
  "unit": "reps",
  "t": [
   2,
   5,
   8
  ]
 },
 {
  "id": "fl-pullup",
  "name": "Front Lever Pull-Up",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "full-fl-row"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "victorian-cross",
  "name": "Victorian Cross",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "full-fl",
   "iron-cross"
  ],
  "unit": "sec",
  "t": [
   1,
   2,
   3
  ],
  "star": true,
  "note": "Dream tier — front-lever body held flat at ring height"
 },
 {
  "id": "back-lever-skin-cat-volume",
  "name": "Skin-the-Cat Volume",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "skin-the-cat",
   "bridge-wheel"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Shoulder-prep volume before back lever loading"
 },
 {
  "id": "tuck-bl",
  "name": "Tuck Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "back-lever-skin-cat-volume"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ],
  "note": "2026 goal: 15s"
 },
 {
  "id": "adv-tuck-bl",
  "name": "Adv. Tuck Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "tuck-bl"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "frog-back-lever",
  "name": "Frog Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "adv-tuck-bl"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "piked-straddle-back-lever",
  "name": "Piked-Straddle Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "frog-back-lever"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "straddle-bl",
  "name": "Straddle Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "piked-straddle-back-lever"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "half-lay-back-lever",
  "name": "Half-Lay Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "straddle-bl"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   12
  ]
 },
 {
  "id": "full-bl",
  "name": "Full Back Lever",
  "branch": "Horizontal Pull",
  "family": "cal",
  "req": [
   "half-lay-back-lever"
  ],
  "unit": "sec",
  "t": [
   3,
   8,
   15
  ]
 },
 {
  "id": "situp",
  "name": "Sit-Up",
  "branch": "Core",
  "family": "cal",
  "req": [],
  "unit": "reps",
  "t": [
   20,
   35,
   50
  ]
 },
 {
  "id": "plank",
  "name": "Plank",
  "branch": "Core",
  "family": "cal",
  "req": [],
  "unit": "sec",
  "t": [
   60,
   90,
   120
  ],
  "note": "Mastered — 2 min"
 },
 {
  "id": "hollow-body",
  "name": "Hollow Body Hold",
  "branch": "Core",
  "family": "cal",
  "req": [
   "situp"
  ],
  "unit": "sec",
  "t": [
   20,
   40,
   60
  ]
 },
 {
  "id": "v-up",
  "name": "V-Up",
  "branch": "Core",
  "family": "cal",
  "req": [
   "hollow-body"
  ],
  "unit": "reps",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "lsit-compression",
  "name": "L-Sit Compression",
  "branch": "Core",
  "family": "cal",
  "req": [
   "situp"
  ],
  "unit": "reps",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "tucked-lsit",
  "name": "Tucked L-Sit",
  "branch": "Core",
  "family": "cal",
  "req": [
   "lsit-compression"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "note": "Knees tucked — the L-sit entry hold"
 },
 {
  "id": "lsit",
  "name": "L-Sit",
  "branch": "Core",
  "family": "cal",
  "req": [
   "tucked-lsit"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "star": true,
  "note": "2026 goal: 30s"
 },
 {
  "id": "straddle-sit",
  "name": "Straddle-Sit",
  "branch": "Core",
  "family": "cal",
  "req": [
   "lsit"
  ],
  "unit": "sec",
  "t": [
   5,
   8,
   12
  ]
 },
 {
  "id": "tucked-vsit",
  "name": "Tucked V-Sit",
  "branch": "Core",
  "family": "cal",
  "req": [
   "lsit"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Legs lifting toward vertical, knees bent"
 },
 {
  "id": "v-sit",
  "name": "V-Sit",
  "branch": "Core",
  "family": "cal",
  "req": [
   "tucked-vsit"
  ],
  "unit": "sec",
  "t": [
   1,
   2,
   3
  ]
 },
 {
  "id": "tucked-manna",
  "name": "Tucked Manna",
  "branch": "Core",
  "family": "cal",
  "req": [
   "v-sit"
  ],
  "unit": "sec",
  "t": [
   1,
   3,
   5
  ],
  "note": "Hips shifting behind the hands, knees tucked"
 },
 {
  "id": "manna",
  "name": "Manna",
  "branch": "Core",
  "family": "cal",
  "req": [
   "tucked-manna"
  ],
  "unit": "sec",
  "t": [
   1,
   3,
   5
  ],
  "star": true,
  "note": "Dream tier — gymnast territory"
 },
 {
  "id": "side-plank",
  "name": "Side Plank",
  "branch": "Core",
  "family": "cal",
  "req": [
   "plank"
  ],
  "unit": "sec",
  "t": [
   45,
   90,
   150
  ],
  "note": "Lateral-chain stability, each side"
 },
 {
  "id": "tucked-dragon-flag",
  "name": "Tucked Dragon Flag",
  "branch": "Core",
  "family": "cal",
  "req": [
   "hollow-body"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ],
  "note": "Knees tucked — the dragon-flag entry"
 },
 {
  "id": "one-leg-dragon-flag",
  "name": "One-Leg Dragon Flag",
  "branch": "Core",
  "family": "cal",
  "req": [
   "tucked-dragon-flag"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "straddle-dragon-flag",
  "name": "Straddle Dragon Flag",
  "branch": "Core",
  "family": "cal",
  "req": [
   "tucked-dragon-flag"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "dragon-flag",
  "name": "Dragon Flag",
  "branch": "Core",
  "family": "cal",
  "req": [
   "one-leg-dragon-flag",
   "straddle-dragon-flag"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "windshield-wipers",
  "name": "Windshield Wipers",
  "branch": "Core",
  "family": "cal",
  "req": [
   "dragon-flag"
  ],
  "unit": "reps",
  "t": [
   4,
   8,
   12
  ],
  "note": "Hanging, legs together, side to side"
 },
 {
  "id": "ab-rollout",
  "name": "Standing Ab Rollout",
  "branch": "Core",
  "family": "cal",
  "req": [
   "hollow-body"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "2026 goal: 5 full standing rollouts"
 },
 {
  "id": "bw-squat",
  "name": "Bodyweight Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [],
  "unit": "reps",
  "t": [
   20,
   40,
   60
  ],
  "note": "Mastered — 60 reps"
 },
 {
  "id": "ankle-mobility-squat",
  "name": "Ankle Mobility (Squat)",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "bw-squat",
   "ankle-dorsiflexion"
  ],
  "tiers": {
   "u": "Knee-over-toe range measured",
   "p": "Full-depth squat, heels down, no wedge",
   "m": "Range holds without daily work"
  },
  "kind": "bridge"
 },
 {
  "id": "split-squat",
  "name": "Split Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "bw-squat"
  ],
  "unit": "reps",
  "t": [
   8,
   15,
   20
  ],
  "note": "Unlock implied by squat mastery"
 },
 {
  "id": "single-leg-balance",
  "name": "Single-Leg Balance",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "split-squat"
  ],
  "unit": "sec",
  "t": [
   30,
   45,
   60
  ],
  "kind": "bridge",
  "note": "Stable stand each leg — pistol prerequisite"
 },
 {
  "id": "nordic-anchor-setup",
  "name": "Nordic Anchor & Partials",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "split-squat"
  ],
  "tiers": {
   "u": "Safe anchor setup found",
   "p": "Partial-range negatives controlled",
   "m": "Setup + warm-up routine automatic"
  },
  "kind": "bridge"
 },
 {
  "id": "cossack-squat",
  "name": "Cossack Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "split-squat"
  ],
  "unit": "reps",
  "t": [
   4,
   7,
   10
  ]
 },
 {
  "id": "sissy-squat",
  "name": "Sissy Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "split-squat"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ]
 },
 {
  "id": "hawaiian-squat",
  "name": "Hawaiian Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "cossack-squat"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ]
 },
 {
  "id": "shrimp-squat",
  "name": "Shrimp Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "split-squat"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ],
  "star": true,
  "note": "2026 goal: 12"
 },
 {
  "id": "pistol-box-negative",
  "name": "Pistol Box Negative",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "single-leg-balance",
   "cossack-squat"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "kind": "bridge",
  "note": "Controlled lower to a box — the pistol bridge"
 },
 {
  "id": "pistol-squat",
  "name": "Pistol Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "pistol-box-negative"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   12
  ]
 },
 {
  "id": "dragon-squat",
  "name": "Dragon Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "pistol-squat"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ]
 },
 {
  "id": "makarov-squat",
  "name": "Makarov Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "cossack-squat",
   "pistol-squat"
  ],
  "unit": "reps",
  "t": [
   2,
   4,
   8
  ],
  "note": "Pistol-cossack blend — extended leg abducts through the rep"
 },
 {
  "id": "sideways-dragon-pistol-squat",
  "name": "Sideways Dragon Pistol Squat",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "dragon-squat"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "Body turned sideways — hardest dragon-family variant"
 },
 {
  "id": "lunge",
  "name": "Lunge",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "bw-squat"
  ],
  "unit": "reps",
  "t": [
   10,
   18,
   30
  ],
  "note": "Forward / reverse / lateral — foundational unilateral pattern"
 },
 {
  "id": "calf-raise",
  "name": "Calf Raise",
  "branch": "Legs",
  "family": "cal",
  "req": [],
  "unit": "reps",
  "t": [
   15,
   25,
   40
  ],
  "note": "Standing / donkey / bent-knee variants"
 },
 {
  "id": "single-leg-calf-raise",
  "name": "Single-Leg Calf Raise",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "calf-raise"
  ],
  "unit": "reps",
  "t": [
   10,
   18,
   30
  ]
 },
 {
  "id": "tib-raise",
  "name": "Anterior Tib Raise",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "ankle-mobility-squat"
  ],
  "unit": "reps",
  "t": [
   15,
   22,
   30
  ],
  "note": "Shin-muscle accessory — knee & ankle resilience"
 },
 {
  "id": "reverse-nordic-curl",
  "name": "Reverse Nordic Curl",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "sissy-squat"
  ],
  "unit": "reps",
  "t": [
   8,
   14,
   20
  ],
  "note": "Kneeling lean-back — quad-focused counterpart to the nordic curl"
 },
 {
  "id": "nordic-negative",
  "name": "Nordic Curl Negative",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "sissy-squat",
   "nordic-anchor-setup"
  ],
  "unit": "reps",
  "t": [
   3,
   6,
   10
  ],
  "note": "Controlled 5s lowering"
 },
 {
  "id": "nordic-curl",
  "name": "Nordic Curl",
  "branch": "Legs",
  "family": "cal",
  "req": [
   "nordic-negative"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   8
  ],
  "star": true
 },
 {
  "id": "bar-swing",
  "name": "Bar Swing",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "active-hang"
  ],
  "tiers": {
   "u": "Controlled hollow-to-arch swing, hips leading",
   "p": "Swing to shoulder height at both ends",
   "m": "Big relaxed swing with a regrip at the dead point"
  },
  "kind": "foundation"
 },
 {
  "id": "swing-regrip",
  "name": "Swing Hop & Regrip",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-swing"
  ],
  "tiers": {
   "u": "Release and regrip both hands at the back-swing peak",
   "p": "Hop with visible air time",
   "m": "Hop between grips (over to under) on consecutive swings"
  },
  "kind": "foundation"
 },
 {
  "id": "monkey-bar-traverse",
  "name": "Monkey Bar Traverse",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "active-hang"
  ],
  "tiers": {
   "u": "Traverse the full set, one rung at a time",
   "p": "Skip a rung, there and back",
   "m": "Skip two rungs with a swing between each"
  },
  "star": true
 },
 {
  "id": "lache",
  "name": "Lache (Bar to Bar)",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "swing-regrip",
   "monkey-bar-traverse"
  ],
  "tiers": {
   "u": "Release from a swing and catch a bar within reach",
   "p": "Clear a 1 m gap",
   "m": "Clear 1.5 m or link several in a row"
  }
 },
 {
  "id": "bar-kip",
  "name": "Bar Kip",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-swing",
   "toes-to-bar"
  ],
  "tiers": {
   "u": "Kip to support from a jump or with a band",
   "p": "Clean long-hang kip to support",
   "m": "3 consecutive kips"
  }
 },
 {
  "id": "back-hip-circle",
  "name": "Back Hip Circle",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "pullover"
  ],
  "tiers": {
   "u": "Cast and circle with bent arms or a spot",
   "p": "Clean straight-arm circle back to support",
   "m": "3 circles connected"
  }
 },
 {
  "id": "underswing-dismount",
  "name": "Underswing Dismount",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-swing",
   "toes-to-bar"
  ],
  "tiers": {
   "u": "Toes to the bar, shoot out and land on your feet",
   "p": "Shoot past 1.5 m with a stuck landing",
   "m": "Cast underswing from support past 2 m"
  }
 },
 {
  "id": "bar-180",
  "name": "Swing 180",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "swing-regrip"
  ],
  "tiers": {
   "u": "Half turn on the bar with one hand always on",
   "p": "Release both hands, turn 180 and catch",
   "m": "Linked 180s in both directions"
  }
 },
 {
  "id": "pull-180",
  "name": "180 Pull-Up",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "explosive-pullup-chest"
  ],
  "tiers": {
   "u": "Explosive pull, switch grip at the top",
   "p": "Pull, turn 180 in the air, catch",
   "m": "3 in a row, both directions"
  }
 },
 {
  "id": "pull-360",
  "name": "360 Pull (Bar Spin)",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "pull-180",
   "waist-pullup"
  ],
  "tiers": {
   "u": "Full 360 with a low catch",
   "p": "Clean 360 caught with bent arms",
   "m": "360 into another pull without resetting"
  },
  "star": true
 },
 {
  "id": "swing-360",
  "name": "Swing 360",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-180"
  ],
  "tiers": {
   "u": "Release at the front peak, spin 360, catch any way",
   "p": "Clean catch with both hands together",
   "m": "Linked straight into the next swing"
  },
  "star": true
 },
 {
  "id": "bar-540",
  "name": "540",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "pull-360",
   "swing-360"
  ],
  "tiers": {
   "u": "540 landing on the ground under the bar",
   "p": "540 caught on the bar",
   "m": "Consistent on demand"
  }
 },
 {
  "id": "bar-720",
  "name": "720",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-540"
  ],
  "tiers": {
   "u": "720 attempted with a safe bail",
   "p": "720 caught",
   "m": "Consistent on demand"
  },
  "star": true
 },
 {
  "id": "muscle-up-360",
  "name": "Muscle-Up 360",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "muscle-up",
   "pull-360"
  ],
  "tiers": {
   "u": "Muscle-up, spin 360 above the bar, land in support with a spot",
   "p": "Clean catch in support",
   "m": "Linked into a dip or second rep"
  }
 },
 {
  "id": "alley-oop",
  "name": "Alley-Oop",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "swing-360"
  ],
  "tiers": {
   "u": "Back-swing release with a half turn",
   "p": "Full alley-oop 360 caught",
   "m": "Linked from a swing without a reset"
  }
 },
 {
  "id": "baby-giant",
  "name": "Baby Giant",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "bar-kip",
   "back-hip-circle"
  ],
  "tiers": {
   "u": "Cast to horizontal and swing down under control",
   "p": "Bent-arm circle back to support",
   "m": "3 baby giants connected"
  }
 },
 {
  "id": "giant",
  "name": "Giant Swing",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "baby-giant"
  ],
  "tiers": {
   "u": "Giant with straps or a spot",
   "p": "One clean giant, straight arms",
   "m": "3 giants connected"
  },
  "star": true
 },
 {
  "id": "shrimp-flip",
  "name": "Shrimp Flip",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "swing-regrip",
   "back-hip-circle"
  ],
  "tiers": {
   "u": "Forward rotation over the bar with a spot or into a pit",
   "p": "Shrimp flip caught on the bar",
   "m": "Linked from a swing"
  }
 },
 {
  "id": "flyaway",
  "name": "Flyaway",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "underswing-dismount"
  ],
  "tiers": {
   "u": "Tucked flyaway into a pit or with a spot",
   "p": "Tucked flyaway to feet on a mat",
   "m": "Layout flyaway, stuck landing"
  },
  "star": true
 },
 {
  "id": "front-flyaway",
  "name": "Front Flyaway",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "flyaway"
  ],
  "tiers": {
   "u": "Front flyaway with a spot",
   "p": "To feet on a mat",
   "m": "Stuck landing on demand"
  }
 },
 {
  "id": "geinger",
  "name": "Geinger",
  "branch": "Bar Dynamics",
  "family": "cal",
  "req": [
   "giant",
   "flyaway",
   "swing-360"
  ],
  "tiers": {
   "u": "Drilled into a pit with a spot",
   "p": "Release, half turn, regrasp",
   "m": "Linked out of a giant"
  }
 },
 {
  "id": "active-flexibility-basics",
  "name": "Active Flexibility Basics",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [],
  "tiers": {
   "u": "End-range contractions understood + tried",
   "p": "Pulses and loaded holds in the weekly routine",
   "m": "Every stretch has an active component"
  },
  "kind": "foundation"
 },
 {
  "id": "shoulder-flexion",
  "name": "Shoulder Flexion",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "active-flexibility-basics"
  ],
  "tiers": {
   "u": "Wall slides clean",
   "p": "Arms overhead, ribs down, no arch",
   "m": "Full overhead range — handstand-line ready"
  },
  "kind": "foundation"
 },
 {
  "id": "thoracic-extension",
  "name": "Thoracic Extension",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "active-flexibility-basics"
  ],
  "tiers": {
   "u": "Foam-roller extensions daily",
   "p": "Visible upper-back extension in bridge photos",
   "m": "Bend comes from the T-spine, not the lower back"
  },
  "kind": "foundation"
 },
 {
  "id": "hip-rotation",
  "name": "Hip Rotation",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "active-flexibility-basics"
  ],
  "tiers": {
   "u": "90/90 sits comfortable both sides",
   "p": "Internal + external rotation drills weekly",
   "m": "Rotation never limits a pose"
  },
  "kind": "foundation"
 },
 {
  "id": "ankle-dorsiflexion",
  "name": "Ankle Dorsiflexion",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [],
  "tiers": {
   "u": "Knee-to-wall measured",
   "p": "Range increasing, squat deepening",
   "m": "Full-depth squat and pistol support"
  },
  "kind": "foundation"
 },
 {
  "id": "cat-cow",
  "name": "Cat / Cow",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [],
  "tiers": {
   "u": "Segmental flexion/extension through the spine",
   "p": "Daily warm-up, moving one vertebra at a time",
   "m": "Spine articulates smoothly, no flat or stuck segments"
  },
  "kind": "foundation"
 },
 {
  "id": "shoulder-mobility-drills",
  "name": "Shoulder Mobility Drills",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "active-flexibility-basics"
  ],
  "tiers": {
   "u": "Behind-back + prone overhead raises tried",
   "p": "Both in the weekly routine, range increasing",
   "m": "Shoulders open enough that flexion drills feel easy"
  },
  "kind": "foundation"
 },
 {
  "id": "shoulder-dislocates",
  "name": "Shoulder Dislocates",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "shoulder-mobility-drills"
  ],
  "unit": "reps",
  "t": [
   10,
   15,
   20
  ],
  "note": "Pass a band/stick overhead front-to-back; narrow the grip as range opens"
 },
 {
  "id": "deep-squat-hold",
  "name": "Deep Squat Hold",
  "branch": "Mobility Foundations",
  "family": "mob",
  "req": [
   "ankle-dorsiflexion",
   "ankle-mobility-squat"
  ],
  "unit": "sec",
  "t": [
   30,
   60,
   120
  ],
  "note": "Passive ass-to-grass hold — hips, ankles, adductors"
 },
 {
  "id": "touching-toes",
  "name": "Touching Toes",
  "branch": "Flexibility",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "note": "Standing forward fold — the hamstring baseline before loaded pike work"
 },
 {
  "id": "plow-pose",
  "name": "Plow Pose",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "touching-toes"
  ],
  "unit": "sec",
  "t": [
   20,
   40,
   60
  ]
 },
 {
  "id": "pigeon-stretch",
  "name": "Pigeon Stretch",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "hip-rotation"
  ],
  "unit": "sec",
  "t": [
   30,
   60,
   90
  ],
  "note": "Glute / external-hip opener, each side"
 },
 {
  "id": "hamstring-loaded-pike",
  "name": "Loaded Pike",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "plow-pose"
  ],
  "tiers": {
   "u": "Weighted pike stretch, light load",
   "p": "Jefferson curls with control",
   "m": "Loaded end-range feels strong, not scary"
  },
  "kind": "bridge"
 },
 {
  "id": "pike-compression-stretch",
  "name": "Pike Compression",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "hamstring-loaded-pike"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "pancake",
  "name": "Pancake Stretch",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "pike-compression-stretch"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "star": true,
  "note": "2026 goal: 30s. Unlocks press-to-handstand."
 },
 {
  "id": "middle-split-strength",
  "name": "Middle Split Strength",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "pancake"
  ],
  "tiers": {
   "u": "Horse stance 60s",
   "p": "Adductor active strength (side lunges, sliders)",
   "m": "Strength through the full straddle range"
  },
  "kind": "bridge"
 },
 {
  "id": "middle-split",
  "name": "Middle Split",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "middle-split-strength"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "front-split-strength",
  "name": "Front Split Strength",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "pike-compression-stretch"
  ],
  "tiers": {
   "u": "Hip flexor + hamstring active control drills",
   "p": "Sliding to near-split under control",
   "m": "Owns every inch of the range"
  },
  "kind": "bridge"
 },
 {
  "id": "front-split",
  "name": "Front Split",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "front-split-strength"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "note": "= Hanumanasana"
 },
 {
  "id": "standing-split",
  "name": "Standing Split",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "front-split"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "leg-behind-neck",
  "name": "Leg Behind Neck",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "front-split"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "camel-pose",
  "name": "Camel Pose",
  "branch": "Flexibility",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   15,
   30,
   45
  ]
 },
 {
  "id": "bridge-prep",
  "name": "Bridge Prep",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "camel-pose",
   "joint-prep-wrists"
  ],
  "tiers": {
   "u": "Wrists, shoulders, thoracic, glutes each prepped",
   "p": "Tabletop bridge strong and pain-free",
   "m": "Push into a partial wheel with straight-ish arms"
  },
  "kind": "bridge"
 },
 {
  "id": "bridge-wheel",
  "name": "Wheel Pose",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "bridge-prep"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ],
  "note": "Urdhva Dhanurasana — full backbend"
 },
 {
  "id": "lotus-prep",
  "name": "Lotus Prep",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "hip-rotation"
  ],
  "tiers": {
   "u": "Half lotus comfortable, knees quiet",
   "p": "Knee-safe entry steps drilled",
   "m": "Hips open enough that lotus is a hip move, not a knee move"
  },
  "kind": "bridge"
 },
 {
  "id": "lotus",
  "name": "Lotus Pose",
  "branch": "Flexibility",
  "family": "mob",
  "req": [
   "lotus-prep"
  ],
  "unit": "sec",
  "t": [
   30,
   60,
   120
  ]
 },
 {
  "id": "wrist-loading-yoga",
  "name": "Wrist Loading (Yoga)",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "joint-prep-wrists"
  ],
  "tiers": {
   "u": "Wrist warm-up before every arm-balance session",
   "p": "Full bodyweight on hands pain-free 5+ min",
   "m": "Wrists conditioned for daily arm balances"
  },
  "kind": "foundation"
 },
 {
  "id": "hip-compression-arm-balance",
  "name": "Hip Compression",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "wrist-loading-yoga",
   "compression-foundation"
  ],
  "tiers": {
   "u": "Knees-to-chest compression drills",
   "p": "Lifted compression holds (feet off floor)",
   "m": "Compression strong enough for firefly-family poses"
  },
  "kind": "foundation"
 },
 {
  "id": "twist-mobility",
  "name": "Twist Mobility",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "wrist-loading-yoga"
  ],
  "tiers": {
   "u": "Seated + revolved twists daily",
   "p": "Deep twist with straight spine both sides",
   "m": "Twist range never blocks side crow family"
  },
  "kind": "foundation"
 },
 {
  "id": "one-legged-crow",
  "name": "One-Legged Crow",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "crow-pose"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Builds on mastered crow pose (Calisthenics)"
 },
 {
  "id": "crow-exits",
  "name": "Crow Exits & Bails",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "one-legged-crow"
  ],
  "tiers": {
   "u": "Safe forward exit drilled",
   "p": "Side falls relaxed, no wrist panic",
   "m": "Falling out of any arm balance is boring"
  },
  "kind": "bridge"
 },
 {
  "id": "crane-pose",
  "name": "Crane Pose",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "one-legged-crow"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "crow-to-handstand",
  "name": "Crow > Handstand",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "crane-pose",
   "handstand"
  ],
  "unit": "reps",
  "t": [
   1,
   3,
   5
  ],
  "note": "Press transition — needs handstand (Calisthenics)"
 },
 {
  "id": "side-crow",
  "name": "Side Crow",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "crane-pose",
   "twist-mobility"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "flying-pigeon",
  "name": "Flying Pigeon",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "side-crow"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Eka Pada Galavasana"
 },
 {
  "id": "grasshopper",
  "name": "Grasshopper Pose",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "flying-pigeon"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "firefly-pose",
  "name": "Firefly Pose",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "side-crow",
   "hip-compression-arm-balance"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "eight-angle-pose",
  "name": "Eight-Angle Pose",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "side-crow"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "mayurasana",
  "name": "Mayurasana",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "crane-pose"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ]
 },
 {
  "id": "flying-split-balance",
  "name": "Flying Split Arm Balance",
  "branch": "Arm Balances",
  "family": "mob",
  "req": [
   "firefly-pose"
  ],
  "unit": "sec",
  "t": [
   1,
   2,
   3
  ],
  "note": "Eka Pada Koundinyasana — 2026 goal: 3s"
 },
 {
  "id": "tree-pose",
  "name": "Tree Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   15,
   30,
   60
  ],
  "note": "Vrikasana"
 },
 {
  "id": "warrior-ii",
  "name": "Warrior II",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   15,
   30,
   60
  ],
  "note": "Virabhadrasana II"
 },
 {
  "id": "chair-pose",
  "name": "Chair Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   15,
   30,
   60
  ],
  "note": "Utkatasana"
 },
 {
  "id": "boat-pose",
  "name": "Boat Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [],
  "unit": "sec",
  "t": [
   10,
   20,
   40
  ],
  "note": "Navasana — no-hands core hold, distinct mechanism from L-sit"
 },
 {
  "id": "king-dance",
  "name": "King Dancer Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "tree-pose"
  ],
  "unit": "sec",
  "t": [
   10,
   20,
   30
  ]
 },
 {
  "id": "full-king-dancer",
  "name": "Full King Dancer",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "king-dance"
  ],
  "unit": "sec",
  "t": [
   5,
   10,
   15
  ],
  "note": "Both hands overhead, foot to crown"
 },
 {
  "id": "mermaid-pose",
  "name": "Mermaid Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "king-dance"
  ],
  "unit": "sec",
  "t": [
   8,
   15,
   20
  ]
 },
 {
  "id": "king-pigeon",
  "name": "King Pigeon",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "mermaid-pose"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ]
 },
 {
  "id": "full-king-pigeon",
  "name": "Full King Pigeon",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "king-pigeon"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Foot touches head"
 },
 {
  "id": "scorpion-pose",
  "name": "Scorpion Pose",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "king-pigeon",
   "forearm-stand"
  ],
  "unit": "sec",
  "t": [
   3,
   6,
   10
  ],
  "note": "Needs forearm stand (Calisthenics)"
 },
 {
  "id": "hollowback-handstand",
  "name": "Hollowback Handstand",
  "branch": "Yoga Holds",
  "family": "mob",
  "req": [
   "scorpion-pose"
  ],
  "unit": "sec",
  "t": [
   2,
   5,
   10
  ],
  "star": true,
  "note": "Dream tier — scorpion in a handstand"
 },
 {
  "id": "safe-landing",
  "name": "Safe Landing",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Quiet two-foot landings, knees tracking toes",
   "p": "Shoulder rolls out of forward momentum",
   "m": "Landing mechanics are reflex at any height"
  },
  "kind": "foundation"
 },
 {
  "id": "forward-roll",
  "name": "Forward Roll",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "safe-landing"
  ],
  "tiers": {
   "u": "Clean roll from squat",
   "p": "From standing, straight line",
   "m": "Dive roll over a small obstacle"
  },
  "kind": "foundation"
 },
 {
  "id": "backward-roll",
  "name": "Backward Roll",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "safe-landing"
  ],
  "tiers": {
   "u": "Clean backward roll on soft ground",
   "p": "Any surface, straight line",
   "m": "Back extension roll (to push-up plank)"
  },
  "kind": "foundation"
 },
 {
  "id": "jump-tuck-landing",
  "name": "Jump-Tuck-Land",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "safe-landing"
  ],
  "tiers": {
   "u": "Vertical jump + knee grab, stuck landing",
   "p": "Height + fast tuck, 10 in a row",
   "m": "Tuck speed that makes a flip plausible"
  },
  "kind": "foundation"
 },
 {
  "id": "cartwheel",
  "name": "Cartwheel",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "safe-landing"
  ],
  "tiers": {
   "u": "Clean cartwheel both directions",
   "p": "Fast, straight-line, pointed legs",
   "m": "Effortless — a walking-pace habit"
  }
 },
 {
  "id": "handstand-cartwheel-line",
  "name": "Handstand-Cartwheel Line",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "cartwheel",
   "handstand"
  ],
  "tiers": {
   "u": "Cartwheel passes through a real handstand line",
   "p": "Slow-motion cartwheel with pause at vertical",
   "m": "The line is gymnast-straight on film"
  },
  "kind": "bridge"
 },
 {
  "id": "roundoff",
  "name": "Round-Off",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "cartwheel"
  ],
  "tiers": {
   "u": "Cartwheel snap-down to two feet",
   "p": "Rebound pop on landing",
   "m": "Powerful — sets up a back handspring"
  }
 },
 {
  "id": "kip-up",
  "name": "Kip-Up",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "First clean kip-up (soft ground OK)",
   "p": "3 in a row, any surface",
   "m": "Clean in a filmed reel"
  },
  "star": true,
  "note": "2026"
 },
 {
  "id": "trampoline-spotting",
  "name": "First Inversion (Spotted)",
  "branch": "Acrobatics Foundations",
  "family": "mov",
  "req": [
   "jump-tuck-landing"
  ],
  "tiers": {
   "u": "First inversion in a safe environment (tramp/foam/spotter)",
   "p": "Backflip motion comfortable with assistance",
   "m": "Inverting no longer scary in the safe setting"
  },
  "kind": "bridge",
  "note": "No concrete-first rule — inversion practice starts here"
 },
 {
  "id": "round-kick",
  "name": "Round Kick",
  "branch": "Kicks",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Clean roundhouse to head height",
   "p": "Fast, balanced, both legs",
   "m": "Snaps back to stance every time"
  },
  "kind": "foundation"
 },
 {
  "id": "crescent-kick",
  "name": "Crescent Kick",
  "branch": "Kicks",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Inside + outside crescent clean",
   "p": "Height + control both directions",
   "m": "Chambered and sharp, either leg"
  },
  "kind": "foundation"
 },
 {
  "id": "hook-kick",
  "name": "Hook Kick",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "crescent-kick"
  ],
  "tiers": {
   "u": "Recognizable hook to head height",
   "p": "Consistent, both legs",
   "m": "Whips clean — feeds the 540 hook"
  }
 },
 {
  "id": "tornado-kick",
  "name": "Tornado Kick (Cheat 360)",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "round-kick"
  ],
  "tiers": {
   "u": "First landed 360 spin round kick",
   "p": "3 in a row, height held",
   "m": "Clean in a filmed line"
  }
 },
 {
  "id": "pop-360",
  "name": "Pop 360",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "round-kick"
  ],
  "tiers": {
   "u": "First two-foot pop 360 kick",
   "p": "Consistent, real height",
   "m": "Clean in a filmed line"
  },
  "note": "Two-foot takeoff, no cheat step"
 },
 {
  "id": "cheat-540",
  "name": "540 Kick (Cheat 540)",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "tornado-kick"
  ],
  "tiers": {
   "u": "First landed 540 (hyper on kicking leg)",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  },
  "star": true,
  "note": "The classic tricking milestone kick"
 },
 {
  "id": "540-hook",
  "name": "540 Hook (Cheat 720)",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "cheat-540",
   "hook-kick"
  ],
  "tiers": {
   "u": "First landed cheat 720",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  },
  "note": "Cheat takeoff, 180 in-air spin, hook kick"
 },
 {
  "id": "pop-540",
  "name": "Pop 540",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "pop-360",
   "cheat-540"
  ],
  "tiers": {
   "u": "First landed pop 540",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  }
 },
 {
  "id": "pop-720",
  "name": "Pop 720",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "pop-540"
  ],
  "tiers": {
   "u": "First landed pop 720 (pop 540 + hook)",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  }
 },
 {
  "id": "hyperhook",
  "name": "Hyperhook",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "540-hook"
  ],
  "tiers": {
   "u": "First landed hyperhook",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  }
 },
 {
  "id": "jackknife",
  "name": "Jackknife",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "540-hook"
  ],
  "tiers": {
   "u": "First landed jackknife",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  },
  "note": "540 married to a hyper hook"
 },
 {
  "id": "cheat-900",
  "name": "Cheat 900",
  "branch": "Kicks",
  "family": "mov",
  "req": [
   "540-hook"
  ],
  "tiers": {
   "u": "First landed cheat 900",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  },
  "star": true,
  "note": "Dream-tier spin kick"
 },
 {
  "id": "cartwheel-pop",
  "name": "Cartwheel Pop",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "cartwheel"
  ],
  "tiers": {
   "u": "Hip lift + pop off the hands felt",
   "p": "Visible airtime on the pop",
   "m": "Pop strong enough to feed an aerial"
  },
  "kind": "bridge"
 },
 {
  "id": "no-handed-cartwheel",
  "name": "No-Handed Cartwheel",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "cartwheel-pop"
  ],
  "tiers": {
   "u": "First clean rep",
   "p": "3 in a row",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "aerial-drills",
  "name": "Aerial Drills",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "no-handed-cartwheel"
  ],
  "tiers": {
   "u": "One-hand + dive cartwheel drills",
   "p": "Takeoff drills with real block/lift",
   "m": "Every drill in the aerial toolbox owned"
  },
  "kind": "bridge"
 },
 {
  "id": "aerial",
  "name": "Aerial",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "aerial-drills"
  ],
  "tiers": {
   "u": "First landed aerial",
   "p": "3 in a row",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "macaco",
  "name": "Macaco",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "kip-up"
  ],
  "tiers": {
   "u": "First macaco (capoeira back-sweep)",
   "p": "Chained 2-3 continuous",
   "m": "Flowing into other moves, filmed"
  }
 },
 {
  "id": "raiz",
  "name": "Raiz",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "aerial"
  ],
  "tiers": {
   "u": "First landed raiz",
   "p": "Consistent height + form",
   "m": "Clean in a filmed reel"
  },
  "note": "Capoeira-derived no-hand takeoff"
 },
 {
  "id": "back-handspring",
  "name": "Back Handspring",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "roundoff"
  ],
  "tiers": {
   "u": "First spotted/soft-ground rep",
   "p": "3 in a row unassisted",
   "m": "Round-off back-handspring line filmed"
  }
 },
 {
  "id": "backflip",
  "name": "Backflip",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "back-handspring",
   "trampoline-spotting"
  ],
  "tiers": {
   "u": "First landed backflip (spotted / soft ground)",
   "p": "3 in a row unassisted",
   "m": "Standing backflip on concrete, filmed"
  },
  "star": true,
  "kind": "capstone",
  "note": "Prime goal. Route: safe landing > tuck-jumps > spotted inversion > handspring > flip."
 },
 {
  "id": "front-flip",
  "name": "Front Flip",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "backflip"
  ],
  "tiers": {
   "u": "First landed front tuck",
   "p": "3 in a row",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "side-flip",
  "name": "Side Flip",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "backflip"
  ],
  "tiers": {
   "u": "First landed side flip (soft ground)",
   "p": "3 in a row",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "gainer",
  "name": "Gainer",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "backflip"
  ],
  "tiers": {
   "u": "First landed gainer (spotted/soft ground)",
   "p": "3 in a row unassisted",
   "m": "Clean in a filmed reel"
  },
  "note": "Backward flip off a forward-traveling takeoff"
 },
 {
  "id": "webster",
  "name": "Webster",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "front-flip"
  ],
  "tiers": {
   "u": "First one-leg front flip landed",
   "p": "Consistent",
   "m": "In a tricking line, filmed"
  }
 },
 {
  "id": "flash-kick",
  "name": "Flash Kick",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "backflip"
  ],
  "tiers": {
   "u": "First landed flash kick (back layout + kick)",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  }
 },
 {
  "id": "butterfly-kick",
  "name": "Butterfly Kick",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "aerial"
  ],
  "tiers": {
   "u": "First clean b-kick",
   "p": "Height + full layout",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "moon-kick",
  "name": "Moon Kick",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "butterfly-kick"
  ],
  "tiers": {
   "u": "First recognizable attempt landed",
   "p": "Consistent height + form",
   "m": "Clean in a filmed reel"
  }
 },
 {
  "id": "full-twist",
  "name": "Full Twist",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "backflip"
  ],
  "tiers": {
   "u": "First landed backflip with a full 360 twist",
   "p": "3 in a row",
   "m": "Clean in a filmed line"
  },
  "note": "One of the three foundational twists"
 },
 {
  "id": "corkscrew",
  "name": "Corkscrew",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "aerial",
   "backflip"
  ],
  "tiers": {
   "u": "First landed cork (spotted)",
   "p": "3 in a row unassisted",
   "m": "Clean in a filmed reel"
  },
  "note": "Off-axis backward twisting flip"
 },
 {
  "id": "b-twist",
  "name": "Butterfly Twist",
  "branch": "Flips & Twists",
  "family": "mov",
  "req": [
   "butterfly-kick"
  ],
  "tiers": {
   "u": "First landed 360 twist",
   "p": "Consistent",
   "m": "In a tricking line, filmed"
  },
  "star": true,
  "note": "Tricking capstone twist"
 },
 {
  "id": "toprock",
  "name": "Toprock",
  "branch": "Breaking",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Basic toprock steps on beat",
   "p": "30s of varied toprock without repeating",
   "m": "Toprock with personality — sets up the drop"
  },
  "kind": "foundation",
  "note": "The standing entry — before footwork"
 },
 {
  "id": "six-step",
  "name": "Six-Step",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "toprock"
  ],
  "tiers": {
   "u": "Full six-step slow",
   "p": "On beat with toprock entry",
   "m": "Footwork combo filmed"
  },
  "note": "Breaking footwork foundation"
 },
 {
  "id": "ccs-and-footwork",
  "name": "CCs & Footwork",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "six-step"
  ],
  "tiers": {
   "u": "CCs + 3-step variations",
   "p": "Footwork flows between patterns",
   "m": "A minute of footwork that never repeats"
  },
  "kind": "bridge"
 },
 {
  "id": "freeze-basics",
  "name": "Freezes (Baby / Chair / Turtle)",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "six-step",
   "elbow-lever"
  ],
  "tiers": {
   "u": "Baby freeze held 3s",
   "p": "Chair + turtle freeze, clean entries",
   "m": "Freezes punctuate combos on the beat"
  }
 },
 {
  "id": "advanced-freeze",
  "name": "Airbaby / Hollowback",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "freeze-basics",
   "elbow-lever",
   "bridge-wheel"
  ],
  "tiers": {
   "u": "Airbaby balanced 2s",
   "p": "Airchair or hollowback held clean",
   "m": "Held long and stylish on film"
  }
 },
 {
  "id": "backspin",
  "name": "Backspin",
  "branch": "Breaking",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "One full rotation on the back",
   "p": "3+ rotations, controlled",
   "m": "Fast, tight, used as a combo entry"
  }
 },
 {
  "id": "power-move-conditioning",
  "name": "Power-Move Conditioning",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "six-step"
  ],
  "tiers": {
   "u": "Wrist/hip/shoulder prep routine running",
   "p": "Kick-up to shoulder + momentum drills",
   "m": "Body prepared for windmill volume"
  },
  "kind": "bridge"
 },
 {
  "id": "swipes",
  "name": "Swipes",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "six-step"
  ],
  "tiers": {
   "u": "One clean swipe rotation",
   "p": "3 continuous",
   "m": "Used as a power-move transition"
  }
 },
 {
  "id": "windmills",
  "name": "Windmills",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "ccs-and-footwork",
   "power-move-conditioning"
  ],
  "tiers": {
   "u": "One full rotation",
   "p": "3 continuous rotations",
   "m": "In a filmed reel"
  }
 },
 {
  "id": "halo",
  "name": "Halo",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "windmills"
  ],
  "tiers": {
   "u": "One halo rotation",
   "p": "3 continuous",
   "m": "In a power-move set, filmed"
  },
  "note": "Windmill on the head/forearm"
 },
 {
  "id": "flare",
  "name": "Flare",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "windmills",
   "full-planche"
  ],
  "tiers": {
   "u": "One full flare rotation",
   "p": "3 continuous",
   "m": "In a filmed reel"
  }
 },
 {
  "id": "headspin",
  "name": "Headspin",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "freeze-basics",
   "headstand"
  ],
  "tiers": {
   "u": "Balanced headstand + first quarter-spins",
   "p": "Multiple continuous rotations",
   "m": "Sustained spin with a hand-free 'tap' finish, filmed"
  }
 },
 {
  "id": "nineties",
  "name": "1990 (One-Hand Spin)",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "backspin",
   "one-arm-handstand"
  ],
  "tiers": {
   "u": "One rotation on one hand",
   "p": "3 continuous rotations",
   "m": "In a power-move set, filmed"
  }
 },
 {
  "id": "airflare",
  "name": "Air Flare",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "flare",
   "windmills"
  ],
  "tiers": {
   "u": "One air flare rotation",
   "p": "2-3 chained",
   "m": "In a power-move set, filmed"
  },
  "star": true,
  "note": "Dream tier — breaking's crown"
 },
 {
  "id": "combo-reel-30s",
  "name": "30s Combo Reel",
  "branch": "Breaking",
  "family": "mov",
  "req": [
   "six-step",
   "windmills",
   "freeze-basics"
  ],
  "tiers": {
   "u": "Combo designed: entry, footwork, power, freeze, exit",
   "p": "Full run filmed without a miss",
   "m": "Posted — the breaking proof"
  },
  "kind": "capstone"
 },
 {
  "id": "dance-musicality",
  "name": "Musicality & Counts",
  "branch": "Dance",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Counts 8s reliably in any song",
   "p": "Hits accents on purpose",
   "m": "Moves land ON the music, not near it"
  },
  "kind": "foundation"
 },
 {
  "id": "body-wave",
  "name": "Body Wave",
  "branch": "Dance",
  "family": "mov",
  "req": [],
  "tiers": {
   "u": "Arm wave travels clean through chest",
   "p": "Full-body wave standing",
   "m": "Waves on rhythm in a combo"
  }
 },
 {
  "id": "the-worm",
  "name": "The Worm",
  "branch": "Dance",
  "family": "mov",
  "req": [
   "body-wave"
  ],
  "tiers": {
   "u": "2 clean waves in a row",
   "p": "5+ continuous waves",
   "m": "In a filmed reel"
  }
 },
 {
  "id": "moonwalk",
  "name": "Moonwalk",
  "branch": "Dance",
  "family": "mov",
  "req": [
   "body-wave"
  ],
  "tiers": {
   "u": "Basic backslide, 2 metres",
   "p": "Smooth to music, 15s",
   "m": "In a filmed reel"
  }
 },
 {
  "id": "airwalk",
  "name": "Airwalk",
  "branch": "Dance",
  "family": "mov",
  "req": [
   "moonwalk"
  ],
  "tiers": {
   "u": "Basic motion recognizable",
   "p": "Smooth to music, 15s",
   "m": "In a filmed reel"
  },
  "star": true,
  "note": "2026"
 },
 {
  "id": "glide-combo",
  "name": "Glide Combo",
  "branch": "Dance",
  "family": "mov",
  "req": [
   "moonwalk",
   "airwalk"
  ],
  "tiers": {
   "u": "Two glides linked (side + back)",
   "p": "A 15s illusion routine",
   "m": "Filmed — the floor looks frictionless"
  }
 }
]

export const SKILL_BY_ID: Map<string, Skill> = new Map(SKILLS.map((s) => [s.id, s]))
